const OFFICIAL_API='https://script.google.com/macros/s/AKfycbzOOtrQy-LfaMlTuLhJJD0ibfSuns4mkF4rWhn6BBTekb09O_UG9-aYH-JGMDZ1lekejw/exec';
const CRM_AI_API='https://script.google.com/macros/s/AKfycbzPIlJHqcGWDMeJd_Tc_tpDz-r-vVW9lNXBiVXnD2o0ulVNoGkUHy-Ve3rAxnsWh9dhUQ/exec';
const CACHE_KEY='ava.medical.official.v1',OVERRIDE_KEY='ava.medical.user.overrides.v1';
const APP_VERSION='v1.1.0',APP_BUILD=window.AVA_MEDICAL_BUILD||'local';
const DIRECT_ADVANCE_PAGES=['R01','R02','N01','N02','N05','N07'];
const state={official:null,journey:null,index:0,answers:{},mode:'use',entry:'frontend',draftText:{},intake:null,adminAuthorized:false,adminStatus:'idle',medicalGrowthRate:6,medicalCost:200000,fundingAmount:600000,claimCost:100000,companyPaid:0,companyCoverage:80000,companyRate:100,eliteDeductible:16000,wiseDeductible:8800,age:40,gender:'male',vitality:false,vhis:false,premiumMode:'annual',selectedPlan:'WISE'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function avaEntry(){const value=new URLSearchParams(window.location.search).get('avaEntry');return ['user','admin'].includes(value)?value:'frontend'}
function setEntry(){state.entry=avaEntry();$('.app-shell').dataset.avaEntry=state.entry;$('#editBtn').hidden=state.entry!=='user';$('#status').hidden=state.entry==='frontend';$('#appVersion').textContent=`${APP_VERSION} · build ${APP_BUILD.slice(0,12)}`}
function setStatus(t,cls=''){const e=$('#status');e.textContent=t;e.className='status '+cls}
function cache(){try{return JSON.parse(localStorage.getItem(CACHE_KEY)||'null')}catch{return null}}
function isValidOfficialData(d){return !!d&&typeof d==='object'&&!Array.isArray(d)&&d.version!==undefined&&Array.isArray(d.pages)&&Array.isArray(d.options)}
function saveCache(d){if(!isValidOfficialData(d))throw Error('Official Data contract invalid');localStorage.setItem(CACHE_KEY,JSON.stringify(d))}
function overrides(){try{return JSON.parse(localStorage.getItem(OVERRIDE_KEY)||'{}')}catch{return {}}}
async function jsonFetch(url,opts){const r=await fetch(url,opts);if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(d.status&&d.status!=='success')throw Error(d.message||'API error');return d}
function renderEntry(){if(state.entry==='admin'){if(state.adminAuthorized)showAdmin();else showAdminGate(state.adminStatus==='pending'?'正在由 AVA Studio 驗證管理入口…':'此管理入口需要由 AVA Studio 驗證後開啟。');return}renderHome();if(state.entry==='user')setMode('edit')}
async function bootstrap({render=true}={}){const localCandidate=cache(),local=isValidOfficialData(localCandidate)?localCandidate:null;if(local){state.official=local;setStatus('本機 Official Cache 已載入；正在檢查版本…');if(render)renderEntry()}else setStatus('首次載入：正在讀取 Official Data…');
 try{const v=await jsonFetch(OFFICIAL_API+'?action=checkVersion');if(!local||String(local.version)!==String(v.version)){const full=await jsonFetch(OFFICIAL_API);state.official=full;saveCache(full);setStatus('Official Data 已更新至 '+(full.version||'最新版本'),'success')}else setStatus('Official Data 已是最新版本 '+v.version,'success');if(render)renderEntry()}catch(e){setStatus(local?'雲端版本檢查失敗，暫用本機資料：'+e.message:'未能載入 Official Data：'+e.message,'error');if(!local&&render)renderEntry()}}
function isEnabled(x){return x?.enabled===undefined||x.enabled===true||String(x.enabled).toUpperCase()==='TRUE'}
function allPages(){return (state.official?.pages||[]).filter(p=>isFixed(p)||isEnabled(p))}
const PAGE_ID_MAP={ready_concern:'R01',ready_existing:'R02',ready_company:'R03',ready_case:'R04',ready_layers:'R05',ready_claim:'R06',ready_features:'R07',ready_reflection:'R08',ready_premium:'R09',ready_presentation:'R10',notready_choice:'N01',notready_tradeoff:'N02',notready_cost:'N03',notready_inflation:'N04',notready_funding:'N05',notready_report:'N06',notready_next:'N07'};
function rawPageId(p){return p.page_id||p.pageId||''}
function pageId(p){const id=String(rawPageId(p));return PAGE_ID_MAP[id.toLowerCase()]||id}
function pageName(p){return p.page_name||p.pageName||p.title||pageId(p)}
function isFixed(p){return p.is_fixed===true||String(p.is_fixed).toUpperCase()==='TRUE'}
function journeyPages(j){const ps=allPages();const prefix=j==='ready'?'R':'N';let x=ps.filter(p=>pageId(p).toUpperCase().startsWith(prefix));if(!x.length)x=ps.filter(p=>String(p.page_type||'').toLowerCase().includes(j));x=x.sort((a,b)=>(+a.sort_order||+a.stepOrder||0)-(+b.sort_order||+b.stepOrder||0));if(j==='ready'){const r02=state.answers.R02||state.answers.r02||state.answers.ready_existing||'';if(r02==='no_medical')x=x.filter(p=>pageId(p).toUpperCase()!=='R03')}return x}
function optsFor(p){const id=pageId(p),raw=rawPageId(p),type=p.option_group||p.page_type;const groupMap={R01:'concern',R02:'existing_medical',N01:'medical_choice',N02:'tradeoff_priority',N05:'funding_source',N07:'future_arrangement'};return (state.official?.options||[]).filter(o=>isEnabled(o)&&(()=>{const g=o.option_group||o.pageId||'';return g===id||g===raw||g===type||g===groupMap[id]})()).sort((a,b)=>(+a.sort_order||+a.order||0)-(+b.sort_order||+b.order||0))}
function textFor(p,k){const id=pageId(p),ov=overrides();return ov[id]?.[k]??p[k]??''}
function renderHome(){setMode('use');$('#home').hidden=false;$('#journey').hidden=true;$('#admin').hidden=true;$('#adminGate').hidden=true}
function showAdminGate(message){setMode('use');$('#home').hidden=true;$('#journey').hidden=true;$('#admin').hidden=true;$('#adminGate').hidden=false;$('#adminGateMessage').textContent=message}
function startJourney(j){state.journey=j;state.index=0;$('#home').hidden=true;$('#journey').hidden=false;renderPage()}
function isDirectAdvancePage(id){return DIRECT_ADVANCE_PAGES.includes(String(id).toUpperCase())}
function renderPage(){const ps=journeyPages(state.journey);if(!ps.length){$('#pageCard').innerHTML='<h2>等待 Official Pages</h2><p class="support">Google Sheet 暫時未有可識別的 '+state.journey+' Journey page_id。</p>';$('#progressText').textContent='0 / 0';return}
 state.index=Math.max(0,Math.min(state.index,ps.length-1));const p=ps[state.index],id=pageId(p),os=optsFor(p);$('#progressText').textContent=(state.index+1)+' / '+ps.length;$('#nextBtn').hidden=isDirectAdvancePage(id);
 let body=(isFixed(p)?'<div class="fixed-badge">* 固定頁</div>':'')+'<p class="eyebrow">'+esc(pageName(p))+'</p><h2 class="editable" data-field="title">'+esc(textFor(p,'title'))+'</h2><p class="subtitle editable" data-field="subtitle">'+esc(textFor(p,'subtitle'))+'</p>';
 if(os.length)body+='<div class="options">'+os.map(o=>{const key=o.option_id||o.optionKey||o.display_name||o.title;const name=o.display_name||o.title||key,sub=o.subtitle||o.desc||'';return '<button class="option-card '+(state.answers[id]===key?'selected':'')+'" data-key="'+esc(key)+'"><strong>'+esc(name)+'</strong><small>'+esc(sub)+'</small></button>'}).join('')+'</div>';
 if(id.toUpperCase()==='R03')body+=companyMedicalBlock();
 if(id.toUpperCase()==='R04')body+=claimCaseBlock();
 if(id.toUpperCase()==='R05'||id.toUpperCase()==='R10')body+=readyClaimBlock(id);
 if(id.toUpperCase()==='R06')body+=readyClaimIllustrationBlock();
 if(id.toUpperCase()==='R07')body+=planFeaturesBlockV2();
 if(id.toUpperCase()==='R08')body+=concernReflection();
 if(id.toUpperCase()==='R09')body+=premiumBlockV2();
 if(id.toUpperCase().includes('N03')||String(p.page_type).includes('medical_cost'))body+=costBlock();
 if(id.toUpperCase().includes('N04')||String(p.page_type).includes('inflation'))body+=inflationBlock();
 if(id.toUpperCase().includes('N06')||String(p.page_type).includes('funding_report'))body+=fundingReport();
 $('#pageCard').innerHTML=body;
 $$('.option-card').forEach(b=>b.onclick=()=>{state.answers[id]=b.dataset.key;b.classList.add('selected');b.setAttribute('aria-pressed','true');if(id.toUpperCase()==='N07'&&b.dataset.key==='future_insurance')startJourney('ready');else if(isDirectAdvancePage(id)){state.index++;renderPage()}else renderPage()});
 if(id.toUpperCase()==='R03'){const cc=$('#companyCoverage'),cr=$('#companyRate');if(cc)cc.oninput=()=>{state.companyCoverage=Math.max(0,+cc.value||0);renderPage()};if(cr)cr.oninput=()=>{state.companyRate=Math.max(0,Math.min(100,+cr.value||0));renderPage()}}
 if(id.toUpperCase()==='R10'){$('#presentationBtn').onclick=()=>setMode('presentation')}
 if(['R05','R10'].includes(id.toUpperCase())){const ci=$('#claimCost'),ed=$('#eliteDeductible'),wd=$('#wiseDeductible');if(ci)ci.oninput=()=>{state.claimCost=Math.max(0,+ci.value||0);renderPage()};if(ed)ed.onchange=()=>{state.eliteDeductible=Number(ed.value);renderPage()};if(wd)wd.onchange=()=>{state.wiseDeductible=Number(wd.value);renderPage()}}
 if(id.toUpperCase()==='R06'){const ci=$('#claimCostDirect'),ed=$('#eliteDeductible'),wd=$('#wiseDeductible');if(ci){ci.oninput=()=>{state.claimCost=Math.max(0,Number(ci.value.replace(/[^0-9.]/g,''))||0);refreshClaimIllustration()};ci.onblur=()=>{ci.value=money(state.claimCost)}}if(ed)ed.onchange=()=>{state.eliteDeductible=Number(ed.value);refreshClaimIllustration()};if(wd)wd.onchange=()=>{state.wiseDeductible=Number(wd.value);refreshClaimIllustration()}}
 if(id.toUpperCase()==='R09'){const age=$('#premiumAge'),gender=$('#premiumGender'),mode=$('#premiumMode'),vit=$('#premiumVitality'),vhis=$('#premiumVhis'),ed=$('#premiumEliteDeductible'),wd=$('#premiumWiseDeductible');if(age)age.onchange=()=>{state.age=Math.max(18,+age.value||18);renderPage()};if(gender)gender.onchange=()=>{state.gender=gender.value;renderPage()};if(mode)mode.onchange=()=>{state.premiumMode=mode.value;renderPage()};if(vit)vit.onchange=()=>{state.vitality=vit.checked;renderPage()};if(vhis)vhis.onchange=()=>{state.vhis=vhis.checked;renderPage()};if(ed)ed.onchange=()=>{state.eliteDeductible=Number(ed.value);renderPage()};if(wd)wd.onchange=()=>{state.wiseDeductible=Number(wd.value);renderPage()}}
 if(id.toUpperCase()==='R09')$$('.premium-result').forEach(b=>b.onclick=()=>{state.selectedPlan=b.dataset.productId;renderPage()});
 if(id.toUpperCase()==='N04'){const r=$('#growthRate');if(r)r.oninput=()=>{state.medicalGrowthRate=+r.value;renderPage()}}
 if(id.toUpperCase()==='N06'){const a=$('#fundingAmount');const m=$('#fundingMedicalCost');if(a)a.onchange=()=>{state.fundingAmount=Math.max(0,+a.value||0);renderPage()};if(m)m.onchange=()=>{state.medicalCost=Math.max(0,+m.value||0);renderPage()}}
 applyEditMode()}
function hasCompanyMedical(){const v=state.answers.R02||state.answers.r02||state.answers.ready_existing||'';return v==='company_medical'}
function companyMedicalPaid(cost){if(!hasCompanyMedical())return 0;return Math.min(Math.max(0,+cost||0),state.companyCoverage)*Math.max(0,Math.min(100,state.companyRate))/100}
function companyMedicalBlock(){return '<div class="company-setup"><p class="helper">只需要大概輸入公司醫療可以用到幾多，之後示例會自動先扣公司醫療，再睇個人醫療。</p><div class="form-grid"><label>公司醫療保障額<input id="companyCoverage" type="number" min="0" value="'+state.companyCoverage+'"></label><label>大概賠償比例<input id="companyRate" type="number" min="0" max="100" value="'+state.companyRate+'"></label></div><div class="presentation-callout"><small>公司醫療設定</small><strong>'+money(state.companyCoverage)+' × '+state.companyRate+'%</strong></div></div>'}

function claimCaseIsPublished(x){const cost=Number(x.medical_cost),paid=Number(x.actual_reimbursement);return (x.enabled===true||String(x.enabled).toUpperCase()==='TRUE')&&(x.verified===true||String(x.verified).toUpperCase()==='TRUE')&&Number.isFinite(cost)&&cost>=0&&Number.isFinite(paid)&&paid>=0}
function claimCaseBlock(){const rows=(state.official?.claimCases||state.official?.claim_cases||[]).filter(claimCaseIsPublished);if(!rows.length)return '<div class="empty-official"><strong>實際索償個案暫未發布</strong><p>R04只會顯示已核實且資料完整嘅 Official Claim Case；未有正式資料之前唔會用模擬數字扮成真實個案。</p></div>';const x=rows[0];return '<div class="claim-case"><p class="eyebrow">已發布索償個案</p><h3>'+esc(x.case_title||x.condition_name||'Medical Claim Case')+'</h3><div class="case-metrics"><div><small>醫療總費用</small><strong>'+money(x.medical_cost)+'</strong></div><div><small>實際賠償</small><strong>'+money(x.actual_reimbursement)+'</strong></div><div><small>自己負擔</small><strong>'+money(Math.max(0,(+x.medical_cost||0)-(+x.actual_reimbursement||0)))+'</strong></div></div><p class="helper">'+esc(x.treatment_name||'')+(x.case_date?' · '+esc(x.case_date):'')+'</p><p class="helper">此處為已發布個案資料；之後R05/R06嘅數字屬簡化計劃示例，兩者會清楚分開。</p></div>'}

function readyClaimBlock(id){const products=productData(),cost=Math.max(0,state.claimCost),companyPaid=companyMedicalPaid(cost),remaining=Math.max(0,cost-companyPaid);if(!products.length)return '<div class="empty-official"><strong>計劃資料暫未發布</strong><p>Official product rules 未能提供安全的簡化示例。</p></div>';const summary=hasCompanyMedical()?'<div class="claim-flow"><div><small>醫療費</small><strong>'+money(cost)+'</strong></div><b>→</b><div><small>公司醫療</small><strong>'+money(companyPaid)+'</strong></div><b>→</b><div><small>餘額</small><strong>'+money(remaining)+'</strong></div></div>':'<div class="claim-flow claim-flow--direct"><div><small>醫療費</small><strong>'+money(cost)+'</strong></div><b>→</b><div><small>個人醫療開始處理</small><strong>'+money(remaining)+'</strong></div></div>';const cards=products.map(p=>claimCard(p,remaining,deductibleFor(p.id))).join('');const continuity=id==='R05'&&hasCompanyMedical()?'<div class="continuity-note"><strong>公司醫療係第一層，但未必係永久安排。</strong><p>轉工、停工或退休後，公司醫療可能改變或完結；呢度只係睇現時兩層保障點樣配合。</p></div>':'';const inputs='<div class="form-grid'+(id==='R10'?' ava-agent-only':'')+'"><label>醫療費<input id="claimCost" type="number" min="0" value="'+cost+'"></label></div>';return '<div class="claim-sim"><p class="helper">用一個簡單例子睇：張醫療單大概幫到幾多，最後自己大概需要畀幾多。</p>'+inputs+summary+continuity+'<div class="claim-results">'+cards+'</div>'+(id==='R10'?'<div class="presentation-callout"><small>ONE-CLICK VIEW</small><strong>重點只係：保險幫幾多，你自己大概畀幾多。</strong><button id="presentationBtn" class="ava-button">開始客戶展示</button></div>':'')+'<p class="helper">以上為簡化溝通示例，並非保證賠償；實際賠償按治療項目、保單條款及實際索償結果而定。產品重要條件於下一部分再重點說明。</p></div>'}
function productData(){return window.AVAMedicalProductData?.getProductData(state.official)||[]}
function deductibleFor(id){const options=window.AVAMedicalProductData?.deductibleOptions(state.official,id)||[],selected=id==='ELITE'?state.eliteDeductible:state.wiseDeductible;return selected!==null&&selected!==undefined&&options.includes(Number(selected))?Number(selected):options[0]}
function selectOptions(id,value){return (window.AVAMedicalProductData?.deductibleOptions(state.official,id)||[]).map(x=>'<option value="'+x+'" '+(Number(value)===x?'selected':'')+'>'+money(x)+'</option>').join('')}
function claimCard(product,remaining,deductible){const E=window.AVAMedicalClaimEngine;if(!E||!product.rule)return '';const hasDeductible=product.rule.illustration_method==='deductible_then_cover';if(hasDeductible&&deductible===undefined)return '<article class="claim-result"><strong>'+esc(product.name)+'</strong><p class="helper">此計劃的自付額選項暫未有可核實資料。</p></article>';const x=E.calculate({officialRules:[product.rule],medicalCost:remaining,deductible})[product.id];if(!x)return '';const customer=x.youPay,plan=x.planPay,total=Math.max(remaining,1),customerPct=customer/total*100,percentage=product.rule.illustration_method==='percentage',first=percentage?['plan',plan,'計劃']:['customer',customer,'自己'],second=percentage?['customer',customer,'自己']:['plan',plan,'計劃'];return '<article data-product-id="'+product.id+'" class="claim-result '+(hasDeductible?'claim-result--deductible':'')+'"><div class="claim-result-head"><div><strong>'+esc(product.name)+'</strong>'+(hasDeductible?'<label class="inline-select">自付額：<select id="'+product.id.toLowerCase()+'Deductible">'+selectOptions(product.id,deductible)+'</select></label>':'')+'</div><small>'+(percentage?'約 '+Math.round(x.rate*100)+'% 簡化示例':'自付額由左開始，再由計劃處理')+'</small></div><div class="bar claim-bar" aria-label="'+first[2]+' '+money(first[1])+'，'+second[2]+' '+money(second[1])+'"><span class="'+first[0]+'" style="width:'+(first[0]==='customer'?customerPct:100-customerPct)+'%">'+first[2]+'</span><span class="'+second[0]+'" style="width:'+(second[0]==='customer'?customerPct:100-customerPct)+'%">'+second[2]+'</span></div><div class="claim-bar-labels"><span>'+first[2]+' '+money(first[1])+'</span><span>'+second[2]+' '+money(second[1])+'</span></div><div class="you-pay"><small>你大概需要支付</small><strong>'+money(customer)+'</strong></div></article>'}
function readyClaimIllustrationBlock(){const products=productData(),cost=Math.max(0,state.claimCost),companyPaid=companyMedicalPaid(cost),remaining=Math.max(0,cost-companyPaid);if(!products.length)return '<div class="empty-official"><strong>計劃資料暫未發布</strong><p>Official product rules 未能提供安全的簡化示例。</p></div>';const cards=products.map(p=>claimCard(p,remaining,deductibleFor(p.id))).join('');return '<div class="claim-sim"><div class="claim-flow claim-flow--direct"><div><label for="claimCostDirect">醫療費</label><input id="claimCostDirect" class="claim-cost-input" aria-label="醫療費" inputmode="decimal" type="text" value="'+money(cost)+'"></div><b>→</b><div><small>個人醫療開始處理</small><strong>'+money(remaining)+'</strong></div></div>'+(hasCompanyMedical()?'<div class="continuity-note"><strong>公司醫療先處理 '+money(companyPaid)+'，個人醫療由 '+money(remaining)+' 開始。</strong></div>':'')+'<div class="claim-results">'+cards+'</div><p class="helper">以上為簡化溝通示例，並非保證賠償；實際賠償按治療項目、保單條款及實際索償結果而定。</p></div>'}
function refreshClaimIllustration(){const current=$('.claim-sim');if(!current)return;const holder=document.createElement('div');holder.innerHTML=readyClaimIllustrationBlock();const updated=holder.firstElementChild;for(const selector of ['.claim-flow > div:last-child','.continuity-note','.claim-results']){const old=current.querySelector(selector),next=updated.querySelector(selector);if(old&&next)old.innerHTML=next.innerHTML;else if(old&&!next)old.remove();else if(next&&!old)current.querySelector('.claim-results')?.before(next.cloneNode(true))}for(const id of ['eliteDeductible','wiseDeductible']){const control=$('#'+id);if(control)control.onchange=()=>{state[id]=Number(control.value);refreshClaimIllustration()}}}
function planFeaturesBlockV2(){const products=productData();if(!products.length)return '<p class="helper">Official 計劃資料暫未提供。</p>';const cards=products.map(p=>{const isDeductible=p.rule?.illustration_method==='deductible_then_cover';const mechanism=isDeductible?'先由客戶支付所選自付額，再按計劃條款處理':p.rule?.illustration_method==='percentage'?'按保障項目及上限處理；本 Journey 只用約 '+Math.round(Number(p.rule.default_rate)*100)+'% 簡化示例':'按計劃條款處理';const deductible=isDeductible?(p.deductibles.length?p.deductibles.map(money).join(' · '):'選項暫未核實'):'沒有自付額選項';return '<article class="plan-feature" data-product-id="'+p.id+'"><div class="plan-feature-head"><span>'+p.id+'</span><h3>'+esc(p.name)+'</h3></div><p>'+esc(mechanism)+'</p><p class="helper">自付額：'+esc(deductible)+'</p><details><summary>查看已發布保障重點</summary>'+(p.features.length?'<div class="feature-points">'+p.features.map(x=>'<div><strong>'+esc(x.title||'保障重點')+'</strong><p>'+esc(x.description||'')+'</p></div>').join('')+'</div>':'<p class="helper">暫未有已發布的詳細保障項目。</p>')+'</details></article>'}).join('');const rows=products.map(p=>'<div class="comparison-cell" data-product-id="'+p.id+'"><strong>'+esc(p.name)+'</strong><p>'+esc(p.features.map(x=>x.description).filter(Boolean).join('；')||'暫未有已發布描述')+'</p></div>').join('');return '<section class="plan-features"><div class="presentation-callout"><small>三個計劃，保障方法各有不同</small><strong>先比較保障方法及限制，再按需要睇詳細條款。</strong></div><div class="product-positioning">'+cards+'</div><div class="product-comparison"><h3>已發布產品重點對照</h3><div class="product-comparison-grid">'+rows+'</div><p class="helper">以上只列出 Medical Official 已發布重點；保障及賠償以正式保單條款為準。</p></div></section>'}

function concernReflection(){const key=state.answers.R01||state.answers.r01||state.answers.ready_concern;const option=(state.official?.options||[]).find(o=>isEnabled(o)&&(o.option_id||o.optionKey)===key);const txt=option?.reflection_text||'';return txt?'<div class="concept"><p class="eyebrow">回到你最初關心嘅事情</p><h3>'+esc(txt)+'</h3></div>':'<p class="helper">R01 尚未選擇關注項目；Reflection 會按 stable option_id 顯示 Official reflection_text。</p>'}
function premiumBlockV2(){const P=window.AVAMedicalProductData,products=productData();if(!P||!products.length)return '<p class="helper">Official 保費資料暫未提供。</p>';const controls='<div class="form-grid premium-controls"><label>年齡<input id="premiumAge" type="number" inputmode="numeric" min="18" max="100" step="1" value="'+state.age+'"></label><label>性別<select id="premiumGender"><option value="male" '+(state.gender==='male'?'selected':'')+'>男</option><option value="female" '+(state.gender==='female'?'selected':'')+'>女</option></select></label>'+products.filter(p=>p.rule?.illustration_method==='deductible_then_cover').map(p=>'<label>'+esc(p.name)+'自付額<select id="premium'+(p.id==='ELITE'?'Elite':'Wise')+'Deductible">'+selectOptions(p.id,deductibleFor(p.id))+'</select></label>').join('')+'<label>付款方式<select id="premiumMode"><option value="annual" '+(state.premiumMode==='annual'?'selected':'')+'>年繳</option><option value="monthly" '+(state.premiumMode==='monthly'?'selected':'')+'>月繳</option></select></label></div><div class="premium-toggles"><label><input id="premiumVitality" type="checkbox" '+(state.vitality?'checked':'')+'> AIA Vitality 健康程式</label><label><input id="premiumVhis" type="checkbox" '+(state.vhis?'checked':'')+'> 顯示 VHIS 估算稅務優惠</label></div>';const cards=products.map(p=>{const base=P.lookupPremium(state.official,p.id,{age:state.age,gender:state.gender,deductible:deductibleFor(p.id)});const amount=base===null?null:P.calculatePremium(base,{vitality:state.vitality,vhis:state.vhis,mode:state.premiumMode});return '<button type="button" class="premium-result '+(state.selectedPlan===p.id?'selected':'')+'" data-product-id="'+p.id+'" aria-pressed="'+(state.selectedPlan===p.id)+'"><strong>'+esc(p.name)+'</strong>'+(amount?'<span class="metric">'+money(amount.charged)+'</span><small>保費 /'+(amount.period==='month'?'月':'年')+' · Official 年繳基準 '+money(amount.baseAnnual)+'</small>'+(state.vitality?'<small>保費 9 折；健康程式會費另計 '+money(amount.vitalityFeeAnnual)+'/年</small>':'')+(state.vhis?'<small>VHIS 估算節稅 '+money(amount.taxEstimate)+'/年，並非保費折扣</small>':''):'<span class="premium-unavailable">此組合暫無已核實保費</span>')+'</button>'}).join('');return '<section class="premium-experience">'+controls+'<div class="premium-results">'+cards+'</div><p class="helper">保費按 Official 表格的實際年齡、產品、自付額及靈活計劃性別讀取；月繳按已核實 1.06 因子計算。Vitality 會費與保費分開顯示。VHIS 為按 17% 稅率及每年 HK$8,000 保費上限的示例估算，實際資格及稅務結果須另行核實。</p></section>'}
function cfg(k,d){return state.official?.config?.[k]??d}
function money(n){return new Intl.NumberFormat('en-HK',{style:'currency',currency:'HKD',maximumFractionDigits:0}).format(+n||0)}
function costBlock(){return '<div class="options"><div class="option-card"><strong>腸胃鏡／日間內視鏡</strong><div class="metric">'+money(cfg('medical_cost_endoscopy_min',10000))+'–'+money(cfg('medical_cost_endoscopy_max',25000))+'</div></div><div class="option-card"><strong>通波仔</strong><div class="metric">'+money(cfg('medical_cost_pci_min',100000))+'–'+money(cfg('medical_cost_pci_max',160000))+'</div><small>部分支架／額外器材可能需要額外自費</small></div><div class="option-card"><strong>大型癌症治療情境</strong><div class="metric">'+money(cfg('medical_cost_cancer_min',200000))+'–'+money(cfg('medical_cost_cancer_max',500000))+'+</div><small>手術／化療／標靶／免疫治療等</small></div></div><p class="helper">私人醫療參考情境；實際費用因醫院、醫生、病情、治療方式、藥物及器材而異。</p>'}
function inflationBlock(){const r=(Number.isFinite(state.medicalGrowthRate)?state.medicalGrowthRate:+cfg('medical_inflation_default',6));const base=state.medicalCost||200000;return '<label class="range-control"><strong>年度醫療成本增長假設：'+r.toFixed(1)+'%</strong><input id="growthRate" type="range" min="0" max="12" step="0.5" value="'+r+'"></label><div class="options">'+[0,5,10,20].map(y=>'<div class="option-card"><strong>'+(y?y+'年後':'今日')+'</strong><div class="metric">'+money(base*Math.pow(1+r/100,y))+'</div></div>').join('')+'</div><p class="helper">模擬假設，可調整 0–12%；並非實際未來醫療費用。</p>'}
function fundingReport(){const fund=Object.values(state.answers).find(v=>String(v).startsWith('fund_'))||'尚未選擇';const cost=Math.max(0,+state.medicalCost||0),asset=Math.max(0,+state.fundingAmount||0),remaining=asset-cost,pct=asset>0?Math.min(100,cost/asset*100):100;return '<h3>Medical Funding Report</h3><div class="form-grid"><label>模擬醫療費<input id="fundingMedicalCost" inputmode="decimal" type="number" min="0" value="'+cost+'"></label><label>可用資金<input id="fundingAmount" inputmode="decimal" type="number" min="0" value="'+asset+'"></label></div><p>資金來源：<strong>'+esc(fund)+'</strong></p><div class="bar"><span class="cost" style="width:'+pct+'%">醫療費 '+money(cost)+'</span><span class="remain" style="width:'+(100-pct)+'%">'+(remaining>=0?'餘額 ':'資金差額 ')+money(Math.abs(remaining))+'</span></div><p class="helper">以上只按本次輸入的模擬金額計算，不代表總資產或實際未來醫療費。</p>'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setMode(m){state.mode=m;document.querySelector('.app-shell').dataset.avaMode=m;const presentation=m==='presentation';$('#modeBar').hidden=m==='use';$('#modeLabel').textContent=presentation?'Customer Presentation':m[0].toUpperCase()+m.slice(1);$('#previewBtn').hidden=presentation;$('#saveBtn').hidden=presentation;$('#cancelBtn').textContent=presentation?'Exit presentation':'Cancel';applyEditMode()}
function applyEditMode(){
  $$('.editable').forEach(e=>{
    e.contentEditable=state.mode==='edit';
    if(state.mode==='edit'){
      e.oninput=()=>{
        const p=journeyPages(state.journey)[state.index];
        const id=pageId(p);
        state.draftText[id]??={};
        state.draftText[id][e.dataset.field]=e.textContent;
      };
    }else{
      e.oninput=null;
    }
  });
}
function saveOverrides(){const o=overrides();Object.entries(state.draftText).forEach(([id,v])=>o[id]={...(o[id]||{}),...v});localStorage.setItem(OVERRIDE_KEY,JSON.stringify(o));state.draftText={};setMode('use');renderPage();setStatus('User Layer 已 Save Local','success')}
function showAdmin(){if(!state.adminAuthorized||!MedicalAdminAuth.hasGrant()){showAdminGate('此管理入口需要由 AVA Studio 驗證後開啟。');return}setMode('use');$('#home').hidden=true;$('#journey').hidden=true;$('#adminGate').hidden=true;$('#admin').hidden=false;const d=state.official||{};$('#cloudInfo').textContent='Official API · version '+(d.version||'—');$('#datasetCounts').innerHTML=['pages','options','plans','claimRules','claimCases','premiumSettings'].map(k=>'<p><strong>'+k+'</strong> '+(d[k]?.length||0)+'</p>').join('')}
async function authorizeAdmin(){state.adminStatus='pending';renderEntry();try{await MedicalAdminAuth.exchangeAppLaunch();state.adminAuthorized=true;state.adminStatus='authorized';showAdmin()}catch(_){MedicalAdminAuth.clear();state.adminAuthorized=false;state.adminStatus='failed';showAdminGate('此管理入口需要由 AVA Studio 驗證後開啟。')}}
function manualForm(pref={}){state.intake={source:'manual',...pref};$('#intakePanel').hidden=false;$('#intakePanel').innerHTML='<h3>資料確認</h3><p class="helper">手動輸入與 AI Draft 共用同一確認步驟。此測試版只建立 Draft，不會直接覆寫 Official Sheet。</p><div class="form-grid"><label>類型<select id="fType"><option value="claim_case">Claim Case</option><option value="product_brochure">Product Brochure</option></select></label><label>名稱<input id="fName" value="'+esc(pref.name||'')+'"></label><label>病症／主題<input id="fCondition" value="'+esc(pref.condition||'')+'"></label><label>醫療總費用<input id="fCost" inputmode="decimal" value="'+esc(pref.cost||'')+'"></label><label>實際賠償<input id="fPaid" inputmode="decimal" value="'+esc(pref.paid||'')+'"></label><label>備註<textarea id="fNotes">'+esc(pref.notes||'')+'</textarea></label></div><div class="nav-actions"><button id="confirmDraft" class="ava-button">確認 Draft</button></div>';$('#confirmDraft').onclick=()=>{state.intake={...state.intake,type:$('#fType').value,name:$('#fName').value,condition:$('#fCondition').value,cost:$('#fCost').value,paid:$('#fPaid').value,notes:$('#fNotes').value,confirmed:true};$('#intakePanel').innerHTML='<h3>已確認 Draft</h3><pre>'+esc(JSON.stringify(state.intake,null,2))+'</pre><p class="helper">正式 Official 寫入需接通 Admin authorization / publish contract 後才啟用。</p>'}}
async function aiStudy(file){$('#intakePanel').hidden=false;$('#intakePanel').innerHTML='<p>AI Study：'+esc(file.name)+'…</p>';try{const b64=await fileBase64(file);const d=await jsonFetch(CRM_AI_API,{method:'POST',body:JSON.stringify({action:'parsePolicyDocument',fileData:b64,mimeType:file.type,fileName:file.name,extractionSchema:'ava.medical.claim.v1',temporary:true,version:state.official?.version||'1.0.0'})});const x=Array.isArray(d.data)?d.data[0]:d.data||{};manualForm({name:x.caseName||x.name||file.name,condition:x.conditionName||x.condition||'',cost:x.medicalCost||x.totalCost||'',paid:x.actualReimbursement||x.paidAmount||'',notes:'AI Draft — 必須人工確認'});state.intake.source='ai'}catch(e){$('#intakePanel').innerHTML='<h3>AI 自動讀取暫時未能完成</h3><p class="error">'+esc(e.message)+'</p><p>Medical 使用獨立 extraction schema；如果 CRM backend 尚未支援，請使用手動輸入。</p><button id="fallbackManual" class="ava-button ava-button--secondary">改用手動輸入</button>';$('#fallbackManual').onclick=()=>manualForm({name:file.name})}}
function fileBase64(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]||'');r.onerror=()=>rej(r.error);r.readAsDataURL(file)})}
setEntry();$$('[data-journey]').forEach(b=>b.onclick=()=>startJourney(b.dataset.journey));$('#backBtn').onclick=renderHome;$('#nextBtn').onclick=()=>{state.index++;renderPage()};$('#editBtn').onclick=()=>setMode('edit');$('#previewBtn').onclick=()=>setMode('preview');$('#saveBtn').onclick=saveOverrides;$('#cancelBtn').onclick=()=>{state.draftText={};setMode('use');renderPage()};$('#adminClose').onclick=renderHome;$('#refreshBtn').onclick=async()=>{localStorage.removeItem(CACHE_KEY);await bootstrap({render:false});showAdmin()};$('#manualBtn').onclick=()=>manualForm();$('#aiFile').onchange=e=>{const f=e.target.files?.[0];if(f)aiStudy(f)};if('serviceWorker'in navigator){let controllerChangeReloaded=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(controllerChangeReloaded)return;controllerChangeReloaded=true;window.location.reload()});navigator.serviceWorker.register('sw.js',{scope:'./',updateViaCache:'none'}).then(registration=>registration.update()).catch(()=>{})}(async()=>{if(state.entry==='admin'){await bootstrap({render:false});await authorizeAdmin()}else await bootstrap()})();
