const OFFICIAL_API='https://script.google.com/macros/s/AKfycbzOOtrQy-LfaMlTuLhJJD0ibfSuns4mkF4rWhn6BBTekb09O_UG9-aYH-JGMDZ1lekejw/exec';
const CRM_AI_API='https://script.google.com/macros/s/AKfycbzPIlJHqcGWDMeJd_Tc_tpDz-r-vVW9lNXBiVXnD2o0ulVNoGkUHy-Ve3rAxnsWh9dhUQ/exec';
const CACHE_KEY='ava.medical.official.v1',OVERRIDE_KEY='ava.medical.user.overrides.v1';
const state={official:null,journey:null,index:0,answers:{},mode:'use',draftText:{},intake:null,medicalGrowthRate:6,medicalCost:200000,fundingAmount:600000,claimCost:100000,companyPaid:0,companyCoverage:80000,companyRate:100,wiseDeductible:8800,age:40};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function setStatus(t,cls=''){const e=$('#status');e.textContent=t;e.className='status '+cls}
function cache(){try{return JSON.parse(localStorage.getItem(CACHE_KEY)||'null')}catch{return null}}
function saveCache(d){localStorage.setItem(CACHE_KEY,JSON.stringify(d))}
function overrides(){try{return JSON.parse(localStorage.getItem(OVERRIDE_KEY)||'{}')}catch{return {}}}
async function jsonFetch(url,opts){const r=await fetch(url,opts);if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(d.status&&d.status!=='success')throw Error(d.message||'API error');return d}
async function bootstrap(){const local=cache();if(local){state.official=local;setStatus('本機 Official Cache 已載入；正在檢查版本…');renderHome()}else setStatus('首次載入：正在讀取 Official Data…');
 try{const v=await jsonFetch(OFFICIAL_API+'?action=checkVersion');if(!local||String(local.version)!==String(v.version)){const full=await jsonFetch(OFFICIAL_API);state.official=full;saveCache(full);setStatus('Official Data 已更新至 '+(full.version||'最新版本'),'success')}else setStatus('Official Data 已是最新版本 '+v.version,'success');renderHome()}catch(e){setStatus(local?'雲端版本檢查失敗，暫用本機資料：'+e.message:'未能載入 Official Data：'+e.message,'error');if(!local)renderHome()}}
function allPages(){return state.official?.pages||[]}
const PAGE_ID_MAP={ready_concern:'R01',ready_existing:'R02',ready_company:'R03',ready_case:'R04',ready_layers:'R05',ready_claim:'R06',ready_features:'R07',ready_reflection:'R08',ready_premium:'R09',ready_presentation:'R10',notready_choice:'N01',notready_tradeoff:'N02',notready_cost:'N03',notready_inflation:'N04',notready_funding:'N05',notready_report:'N06',notready_next:'N07'};
function rawPageId(p){return p.page_id||p.pageId||''}
function pageId(p){const id=String(rawPageId(p));return PAGE_ID_MAP[id.toLowerCase()]||id}
function pageName(p){return p.page_name||p.pageName||p.title||pageId(p)}
function isFixed(p){return p.is_fixed===true||String(p.is_fixed).toUpperCase()==='TRUE'}
function journeyPages(j){const ps=allPages();const prefix=j==='ready'?'R':'N';let x=ps.filter(p=>pageId(p).toUpperCase().startsWith(prefix));if(!x.length)x=ps.filter(p=>String(p.page_type||'').toLowerCase().includes(j));x=x.sort((a,b)=>(+a.sort_order||+a.stepOrder||0)-(+b.sort_order||+b.stepOrder||0));if(j==='ready'){const r02=state.answers.R02||state.answers.r02||state.answers.ready_existing||'';if(r02==='no_medical')x=x.filter(p=>pageId(p).toUpperCase()!=='R03')}return x}
function optsFor(p){const id=pageId(p),raw=rawPageId(p),type=p.option_group||p.page_type;const groupMap={R01:'concern',R02:'existing_medical',N01:'medical_choice',N02:'tradeoff_priority',N05:'funding_source',N07:'future_arrangement'};return (state.official?.options||[]).filter(o=>{const g=o.option_group||o.pageId||'';return g===id||g===raw||g===type||g===groupMap[id]}).sort((a,b)=>(+a.sort_order||+a.order||0)-(+b.sort_order||+b.order||0))}
function textFor(p,k){const id=pageId(p),ov=overrides();return ov[id]?.[k]??p[k]??''}
function renderHome(){$('#home').hidden=false;$('#journey').hidden=true;$('#admin').hidden=true}
function startJourney(j){state.journey=j;state.index=0;$('#home').hidden=true;$('#journey').hidden=false;renderPage()}
function renderPage(){const ps=journeyPages(state.journey);if(!ps.length){$('#pageCard').innerHTML='<h2>等待 Official Pages</h2><p class="support">Google Sheet 暫時未有可識別的 '+state.journey+' Journey page_id。</p>';$('#progressText').textContent='0 / 0';return}
 state.index=Math.max(0,Math.min(state.index,ps.length-1));const p=ps[state.index],id=pageId(p),os=optsFor(p);$('#progressText').textContent=(state.index+1)+' / '+ps.length;
 let body=(isFixed(p)?'<div class="fixed-badge">* 固定頁</div>':'')+'<p class="eyebrow">'+esc(pageName(p))+'</p><h2 class="editable" data-field="title">'+esc(textFor(p,'title'))+'</h2><p class="subtitle editable" data-field="subtitle">'+esc(textFor(p,'subtitle'))+'</p>';
 if(os.length)body+='<div class="options">'+os.map(o=>{const key=o.option_id||o.optionKey||o.display_name||o.title;const name=o.display_name||o.title||key,sub=o.subtitle||o.desc||'';return '<button class="option-card '+(state.answers[id]===key?'selected':'')+'" data-key="'+esc(key)+'"><strong>'+esc(name)+'</strong><small>'+esc(sub)+'</small></button>'}).join('')+'</div>';
 if(id.toUpperCase()==='R03')body+=companyMedicalBlock();
 if(id.toUpperCase()==='R04')body+=claimCaseBlock();
 if(id.toUpperCase()==='R05'||id.toUpperCase()==='R06'||id.toUpperCase()==='R10')body+=readyClaimBlock(id);
 if(id.toUpperCase()==='R07')body+=planFeaturesBlock();
 if(id.toUpperCase()==='R08')body+=concernReflection();
 if(id.toUpperCase()==='R09')body+=premiumBlock();
 if(id.toUpperCase().includes('N03')||String(p.page_type).includes('medical_cost'))body+=costBlock();
 if(id.toUpperCase().includes('N04')||String(p.page_type).includes('inflation'))body+=inflationBlock();
 if(id.toUpperCase().includes('N06')||String(p.page_type).includes('funding_report'))body+=fundingReport();
 $('#pageCard').innerHTML=body;
 $('.option-card').forEach(b=>b.onclick=()=>{state.answers[id]=b.dataset.key;if(id.toUpperCase()==='N07'&&b.dataset.key==='future_insurance')startJourney('ready');else renderPage()});
 if(id.toUpperCase()==='R03'){const cc=$('#companyCoverage'),cr=$('#companyRate');if(cc)cc.oninput=()=>{state.companyCoverage=Math.max(0,+cc.value||0);renderPage()};if(cr)cr.oninput=()=>{state.companyRate=Math.max(0,Math.min(100,+cr.value||0));renderPage()}}
 if(['R05','R06','R10'].includes(id.toUpperCase())){const ci=$('#claimCost'),dd=$('#wiseDeductible');if(ci)ci.oninput=()=>{state.claimCost=Math.max(0,+ci.value||0);renderPage()};if(dd)dd.onchange=()=>{state.wiseDeductible=Math.max(0,+dd.value||0);renderPage()}}
 if(id.toUpperCase()==='R09'){const age=$('#premiumAge');if(age)age.onchange=()=>{state.age=Math.max(18,+age.value||18);renderPage()}}
 if(id.toUpperCase()==='N04'){const r=$('#growthRate');if(r)r.oninput=()=>{state.medicalGrowthRate=+r.value;renderPage()}}
 if(id.toUpperCase()==='N06'){const a=$('#fundingAmount');const m=$('#fundingMedicalCost');if(a)a.onchange=()=>{state.fundingAmount=Math.max(0,+a.value||0);renderPage()};if(m)m.onchange=()=>{state.medicalCost=Math.max(0,+m.value||0);renderPage()}}
 applyEditMode()}
function hasCompanyMedical(){const v=state.answers.R02||state.answers.r02||state.answers.ready_existing||'';return v==='company_medical'}
function companyMedicalPaid(cost){if(!hasCompanyMedical())return 0;return Math.min(Math.max(0,+cost||0),state.companyCoverage)*Math.max(0,Math.min(100,state.companyRate))/100}
function companyMedicalBlock(){return '<div class="company-setup"><p class="helper">只需要大概輸入公司醫療可以用到幾多，之後示例會自動先扣公司醫療，再睇個人醫療。</p><div class="form-grid"><label>公司醫療保障額<input id="companyCoverage" type="number" min="0" value="'+state.companyCoverage+'"></label><label>大概賠償比例<input id="companyRate" type="number" min="0" max="100" value="'+state.companyRate+'"></label></div><div class="presentation-callout"><small>公司醫療設定</small><strong>'+money(state.companyCoverage)+' × '+state.companyRate+'%</strong></div></div>'}

function claimCaseBlock(){const rows=(state.official?.claimCases||state.official?.claim_cases||[]).filter(x=>x.enabled===true||String(x.enabled).toUpperCase()==='TRUE');if(!rows.length)return '<div class="empty-official"><strong>實際索償個案暫未發布</strong><p>R04只會顯示已核實嘅 Official Claim Case；未有正式資料之前唔會用模擬數字扮成真實個案。</p></div>';const x=rows.find(r=>r.verified===true||String(r.verified).toUpperCase()==='TRUE')||rows[0];return '<div class="claim-case"><p class="eyebrow">已發布索償個案</p><h3>'+esc(x.case_title||x.condition_name||'Medical Claim Case')+'</h3><div class="case-metrics"><div><small>醫療總費用</small><strong>'+money(x.medical_cost)+'</strong></div><div><small>實際賠償</small><strong>'+money(x.actual_reimbursement)+'</strong></div><div><small>自己負擔</small><strong>'+money(Math.max(0,(+x.medical_cost||0)-(+x.actual_reimbursement||0)))+'</strong></div></div><p class="helper">'+esc(x.treatment_name||'')+(x.case_date?' · '+esc(x.case_date):'')+'</p><p class="helper">此處為已發布個案資料；之後R05/R06嘅數字屬簡化計劃示例，兩者會清楚分開。</p></div>'}

function readyClaimBlock(id){const E=window.AVAMedicalClaimEngine;if(!E)return '<p class="error">Claim Illustration Engine 未載入。</p>';const rules=state.official?.claimRules||state.official?.claim_rules||[],companyPaid=companyMedicalPaid(state.claimCost),r=E.calculate({officialRules:rules,medicalCost:state.claimCost,companyPaid,deductible:state.wiseDeductible}),remaining=Math.max(0,state.claimCost-companyPaid);const summary=hasCompanyMedical()?'<div class="claim-flow"><div><small>醫療費</small><strong>'+money(state.claimCost)+'</strong></div><b>→</b><div><small>公司醫療</small><strong>'+money(companyPaid)+'</strong></div><b>→</b><div><small>餘額</small><strong>'+money(remaining)+'</strong></div></div>':'<div class="claim-flow claim-flow--direct"><div><small>醫療費</small><strong>'+money(state.claimCost)+'</strong></div><b>→</b><div><small>個人醫療開始處理</small><strong>'+money(remaining)+'</strong></div></div>';const cards=['ELITE','WISE','FLEXI'].map(k=>{const x=r[k];if(!x)return '';const planPct=remaining?Math.max(0,Math.min(100,x.planPay/remaining*100)):0;return '<div class="claim-result"><div class="claim-result-head"><strong>'+esc(x.planName)+'</strong><small>'+(k==='FLEXI'?'約 '+Math.round(x.rate*100)+'% 簡化示例':'自付額後簡化示例')+'</small></div><div class="bar"><span class="cost" style="width:'+planPct+'%">計劃 '+money(x.planPay)+'</span><span class="remain" style="width:'+(100-planPct)+'%">自己 '+money(x.youPay)+'</span></div><div class="you-pay"><small>你大概需要支付</small><strong>'+money(x.youPay)+'</strong></div></div>'}).join('');const continuity=id==='R05'&&hasCompanyMedical()?'<div class="continuity-note"><strong>公司醫療係第一層，但未必係永久安排。</strong><p>轉工、停工或退休後，公司醫療可能改變或完結；呢度只係睇現時兩層保障點樣配合。</p></div>':'';return '<div class="claim-sim"><p class="helper">用一個簡單例子睇：張醫療單大概幫到幾多，最後自己大概需要畀幾多。</p><div class="form-grid"><label>醫療費<input id="claimCost" type="number" min="0" value="'+state.claimCost+'"></label><label>尊耀／睿選示例自付額<input id="wiseDeductible" type="number" min="0" value="'+state.wiseDeductible+'"></label></div>'+summary+continuity+'<div class="claim-results">'+cards+'</div>'+(id==='R10'?'<div class="presentation-callout"><small>ONE-CLICK VIEW</small><strong>重點只係：保險幫幾多，你自己大概畀幾多。</strong></div>':'')+'<p class="helper">以上為簡化溝通示例，並非保證賠償；實際賠償按治療項目、保單條款及實際索償結果而定。產品重要條件於下一部分再重點說明。</p></div>'}
function planFeaturesBlock(){const rows=state.official?.plans||[];const plans=['ELITE','WISE','FLEXI'];const blocks=plans.map(id=>{const related=rows.filter(x=>String(x.plan_id||'').toUpperCase()===id);if(!related.length)return '';const base=related.find(x=>String(x.record_type||'').toUpperCase()==='PLAN')||related[0];const features=related.filter(x=>String(x.record_type||'').toUpperCase()==='FEATURE');return '<article class="plan-feature"><div class="plan-feature-head"><span>'+esc(id)+'</span><h3>'+esc(base.plan_name||base.title||id)+'</h3></div><p>'+esc(base.description||'')+'</p>'+(features.length?'<div class="feature-points">'+features.map(x=>'<div><strong>'+esc(x.title||'重點')+'</strong><p>'+esc(x.description||'')+'</p></div>').join('')+'</div>':'')+'<p class="helper">呢部分係用嚟指出值得留意嘅產品重點；實際保障及賠償仍以正式保單條款為準。</p></article>'}).join('');return '<section class="plan-features"><div class="presentation-callout"><small>由數字返到產品</small><strong>先睇清楚自己大概需要負擔幾多，再了解計劃有咩重要特點。</strong></div>'+blocks+'</section>'}

function concernReflection(){const key=state.answers.R01||state.answers.r01||state.answers.ready_concern;const option=(state.official?.options||[]).find(o=>(o.option_id||o.optionKey)===key);const txt=option?.reflection_text||'';return txt?'<div class="concept"><p class="eyebrow">回到你最初關心嘅事情</p><h3>'+esc(txt)+'</h3></div>':'<p class="helper">R01 尚未選擇關注項目；Reflection 會按 stable option_id 顯示 Official reflection_text。</p>'}
function premiumBlock(){const rows=state.official?.premiumSettings||state.official?.premium_settings||[];const age=state.age;const matches=rows.filter(x=>{const a=+(x.age||x.insured_age||0);return !a||a===age});return '<div class="form-grid"><label>年齡<input id="premiumAge" type="number" min="18" max="100" value="'+age+'"></label></div>'+(matches.length?'<div class="options">'+matches.slice(0,6).map(x=>'<div class="option-card"><strong>'+esc(x.title||x.plan_name||x.plan_id||'Premium')+'</strong><div class="metric">'+money(x.premium||x.value||0)+'</div><small>'+esc(x.description||'Official Premium Data')+'</small></div>').join('')+'</div>':'<p class="helper">目前 Official Premium dataset 未有符合此年齡的資料；不會估算保費。</p>')}
function cfg(k,d){return state.official?.config?.[k]??d}
function money(n){return new Intl.NumberFormat('en-HK',{style:'currency',currency:'HKD',maximumFractionDigits:0}).format(+n||0)}
function costBlock(){return '<div class="options"><div class="option-card"><strong>腸胃鏡／日間內視鏡</strong><div class="metric">'+money(cfg('medical_cost_endoscopy_min',10000))+'–'+money(cfg('medical_cost_endoscopy_max',25000))+'</div></div><div class="option-card"><strong>通波仔</strong><div class="metric">'+money(cfg('medical_cost_pci_min',100000))+'–'+money(cfg('medical_cost_pci_max',160000))+'</div><small>部分支架／額外器材可能需要額外自費</small></div><div class="option-card"><strong>大型癌症治療情境</strong><div class="metric">'+money(cfg('medical_cost_cancer_min',200000))+'–'+money(cfg('medical_cost_cancer_max',500000))+'+</div><small>手術／化療／標靶／免疫治療等</small></div></div><p class="helper">私人醫療參考情境；實際費用因醫院、醫生、病情、治療方式、藥物及器材而異。</p>'}
function inflationBlock(){const r=(Number.isFinite(state.medicalGrowthRate)?state.medicalGrowthRate:+cfg('medical_inflation_default',6));const base=state.medicalCost||200000;return '<label class="range-control"><strong>年度醫療成本增長假設：'+r.toFixed(1)+'%</strong><input id="growthRate" type="range" min="0" max="12" step="0.5" value="'+r+'"></label><div class="options">'+[0,5,10,20].map(y=>'<div class="option-card"><strong>'+(y?y+'年後':'今日')+'</strong><div class="metric">'+money(base*Math.pow(1+r/100,y))+'</div></div>').join('')+'</div><p class="helper">模擬假設，可調整 0–12%；並非實際未來醫療費用。</p>'}
function fundingReport(){const fund=Object.values(state.answers).find(v=>String(v).startsWith('fund_'))||'尚未選擇';const cost=Math.max(0,+state.medicalCost||0),asset=Math.max(0,+state.fundingAmount||0),remaining=asset-cost,pct=asset>0?Math.min(100,cost/asset*100):100;return '<h3>Medical Funding Report</h3><div class="form-grid"><label>模擬醫療費<input id="fundingMedicalCost" inputmode="decimal" type="number" min="0" value="'+cost+'"></label><label>可用資金<input id="fundingAmount" inputmode="decimal" type="number" min="0" value="'+asset+'"></label></div><p>資金來源：<strong>'+esc(fund)+'</strong></p><div class="bar"><span class="cost" style="width:'+pct+'%">醫療費 '+money(cost)+'</span><span class="remain" style="width:'+(100-pct)+'%">'+(remaining>=0?'餘額 ':'資金差額 ')+money(Math.abs(remaining))+'</span></div><p class="helper">以上只按本次輸入的模擬金額計算，不代表總資產或實際未來醫療費。</p>'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setMode(m){state.mode=m;document.querySelector('.app-shell').dataset.avaMode=m;$('#modeBar').hidden=m==='use';$('#modeLabel').textContent=m[0].toUpperCase()+m.slice(1);applyEditMode()}
function applyEditMode(){
  $$('.editable').forEach(e=>{
    e.contentEditable=state.mode==='edit';
    if(state.mode==='edit'){
      e.oninput=()=>{
        const p=journeyPages(state.journey)[state.index];
        const id=pageId(p);
        state.draftText[id]??={};
        state.draftText[id][e.dataset.field]=e.textContent;
      };
    }else{
      e.oninput=null;
    }
  });
}
function saveOverrides(){const o=overrides();Object.entries(state.draftText).forEach(([id,v])=>o[id]={...(o[id]||{}),...v});localStorage.setItem(OVERRIDE_KEY,JSON.stringify(o));state.draftText={};setMode('use');renderPage();setStatus('User Layer 已 Save Local','success')}
function showAdmin(){setMode('use');$('#home').hidden=true;$('#journey').hidden=true;$('#admin').hidden=false;const d=state.official||{};$('#cloudInfo').textContent='Official API · version '+(d.version||'—');$('#datasetCounts').innerHTML=['pages','options','plans','claimRules','claimCases','premiumSettings'].map(k=>'<p><strong>'+k+'</strong> '+(d[k]?.length||0)+'</p>').join('')}
function manualForm(pref={}){state.intake={source:'manual',...pref};$('#intakePanel').hidden=false;$('#intakePanel').innerHTML='<h3>資料確認</h3><p class="helper">手動輸入與 AI Draft 共用同一確認步驟。此測試版只建立 Draft，不會直接覆寫 Official Sheet。</p><div class="form-grid"><label>類型<select id="fType"><option value="claim_case">Claim Case</option><option value="product_brochure">Product Brochure</option></select></label><label>名稱<input id="fName" value="'+esc(pref.name||'')+'"></label><label>病症／主題<input id="fCondition" value="'+esc(pref.condition||'')+'"></label><label>醫療總費用<input id="fCost" inputmode="decimal" value="'+esc(pref.cost||'')+'"></label><label>實際賠償<input id="fPaid" inputmode="decimal" value="'+esc(pref.paid||'')+'"></label><label>備註<textarea id="fNotes">'+esc(pref.notes||'')+'</textarea></label></div><div class="nav-actions"><button id="confirmDraft" class="ava-button">確認 Draft</button></div>';$('#confirmDraft').onclick=()=>{state.intake={...state.intake,type:$('#fType').value,name:$('#fName').value,condition:$('#fCondition').value,cost:$('#fCost').value,paid:$('#fPaid').value,notes:$('#fNotes').value,confirmed:true};$('#intakePanel').innerHTML='<h3>已確認 Draft</h3><pre>'+esc(JSON.stringify(state.intake,null,2))+'</pre><p class="helper">正式 Official 寫入需接通 Admin authorization / publish contract 後才啟用。</p>'}}
async function aiStudy(file){$('#intakePanel').hidden=false;$('#intakePanel').innerHTML='<p>AI Study：'+esc(file.name)+'…</p>';try{const b64=await fileBase64(file);const d=await jsonFetch(CRM_AI_API,{method:'POST',body:JSON.stringify({action:'parsePolicyDocument',fileData:b64,mimeType:file.type,fileName:file.name,extractionSchema:'ava.medical.claim.v1',temporary:true,version:state.official?.version||'1.0.0'})});const x=Array.isArray(d.data)?d.data[0]:d.data||{};manualForm({name:x.caseName||x.name||file.name,condition:x.conditionName||x.condition||'',cost:x.medicalCost||x.totalCost||'',paid:x.actualReimbursement||x.paidAmount||'',notes:'AI Draft — 必須人工確認'});state.intake.source='ai'}catch(e){$('#intakePanel').innerHTML='<h3>AI 自動讀取暫時未能完成</h3><p class="error">'+esc(e.message)+'</p><p>Medical 使用獨立 extraction schema；如果 CRM backend 尚未支援，請使用手動輸入。</p><button id="fallbackManual" class="ava-button ava-button--secondary">改用手動輸入</button>';$('#fallbackManual').onclick=()=>manualForm({name:file.name})}}
function fileBase64(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]||'');r.onerror=()=>rej(r.error);r.readAsDataURL(file)})}
$$('[data-journey]').forEach(b=>b.onclick=()=>startJourney(b.dataset.journey));$('#backBtn').onclick=renderHome;$('#prevBtn').onclick=()=>{state.index--;renderPage()};$('#nextBtn').onclick=()=>{state.index++;renderPage()};$('#editBtn').onclick=()=>{if(!state.journey)startJourney('notready');setMode('edit')};$('#previewBtn').onclick=()=>setMode('preview');$('#saveBtn').onclick=saveOverrides;$('#cancelBtn').onclick=()=>{state.draftText={};setMode('use');renderPage()};$('#adminBtn').onclick=showAdmin;$('#adminClose').onclick=renderHome;$('#refreshBtn').onclick=async()=>{localStorage.removeItem(CACHE_KEY);await bootstrap();showAdmin()};$('#manualBtn').onclick=()=>manualForm();$('#aiFile').onchange=e=>{const f=e.target.files?.[0];if(f)aiStudy(f)};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});bootstrap();